<?php


/**
 * @file
 * Primary module hooks for Boostrap Toolbox Carousel module.
 */

/**
 * Implements hook_theme().
 */
function bootstrap_toolbox_carousel_theme() {
  return [
    'bootstrap_toolbox_media_images_carousel' => [
      'variables' => [
        'images' => [],
        'carousel_id' => '',
        'settings' => [],
      ],
      'template' => 'bootstrap-toolbox-media-images-carousel',
    ],
    'bootstrap_toolbox_entities_carousel' => [
      'variables' => [
        'entities' => [],
        'carousel_id' => '',
        'settings' => [],
      ],
      'template' => 'bootstrap-toolbox-entities-carousel',
    ],
    'views_view_bootstrap_toolbox_carousel_view_style' => [
      'variables' => [
        'view' => NULL,
        'rows' => NULL,
        'options' => NULL,
      ],
      'template' => 'views-view-bootstrap-toolbox-carousel-view-style',
    ],
  ];
}


/**
 * Prepares variables for views-view-bootstrap-toolbox-carousel-view-style.html.twig template.
 */
function template_preprocess_views_view_bootstrap_toolbox_carousel_view_style(array &$variables): void {
  $config = \Drupal::config('bootstrap_toolbox_carousel.settings');
  $selected_library = $config->get('selected_library');
  $variables['carousel_id'] = \Drupal\Component\Utility\Html::getId('carousel-' . uniqid());
  $variables['#attached']['library'][] = 'bootstrap_toolbox_carousel/bootstrap_carousel';

  $view = $variables['view'];
  if ($view && $view->style_plugin instanceof \Drupal\bootstrap_toolbox_carousel\Plugin\views\style\BootstrapToolboxCarouselViewStyle) {
    $variables['options'] = $view->style_plugin->options;
  }

  // Prepare rows for rendering
  $entity_view_builder = \Drupal::entityTypeManager()->getViewBuilder('node');
  foreach ($variables['rows'] as &$row) {
    if (isset($row['#node'])) {
      $row['#node'] = $entity_view_builder->view($row['#node'], $row['#view_mode']);
    }
  }
}


/**
 * Implements hook_theme_suggestions_HOOK_alter() for views templates.
 */
function bootstrap_toolbox_carousel_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];
  if ($view->style_plugin instanceof \Drupal\bootstrap_toolbox_carousel\Plugin\views\style\BootstrapToolboxCarouselViewStyle) {
    $suggestions[] = 'views_view__bootstrap_toolbox_carousel_view_style';
  }
}

